### ISSUE TITLE
[bug] Date/format - toZone removes millisecond information

### ISSUE THREAD

**Issue by ghost** [ValkyrieStudios/utils#26]
A date such as `2024-10-04T12:30:12.345` will be returned as `2024-10-04T12:30:12.000` by the toZone function.

The cause of this is the use of `toLocaleString` [here](https://github.com/ValkyrieStudios/utils/blob/main/lib/date/format.ts#L127), which removes millisecond information.

A possible fix would be:
```diff
- zone_time = new Date(d.toLocaleString(DEFAULT_LOCALE, {timeZone: zone})).getTime();
+ zone_time = new Date(d.toLocaleString(DEFAULT_LOCALE, {timeZone: zone})).getTime() + d.getMilliseconds();
```

**Comment by peterver** [comment]
Fixed in https://github.com/ValkyrieStudios/utils/releases/tag/12.25.0

thanks for reporting @FlorDonnaSanders!
